### ISSUE TITLE
How to download the directory

### ISSUE THREAD

**Issue by shellerto** [Marten4n6/EvilOSX#10]
Is it a victim of the system
Downloaded a directory

i use this command 
use download 
and set path address  but not work .

**Comment by Marten4n6** [comment]
The download module never claimed to support directories, downloading files works fine.
I'll have a look at adding support for directories today, probably make it [ZIP](https://en.wikipedia.org/wiki/Zip_(file_format)) the directory first because then there will be less data to transfer over the network and I can perform a checksum easier.
Thanks for your input as always!
